# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f902766fa8e5e603385711a7020aeb428a986e0590abb735a02a81a7d416795c8a577007808eec6bdeddd80dce1031e20f0d785f3de5ee84862a384a20661cb8

test:
  secret_key_base: 04f942b98df98556a4a02053657a9bae3bb4810adbfcad8dba88304a8c451abb68956c07f0c18c50c12d7547831601c97d415147e6b61c44ebd5f3e671cece9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
